-- FULL ROBLOX GUI WITH ABILITIES
-- Generated by ChatGPT
-- Includes: close, minimize, floating orb, drag, speed, jump, fly, noclip, invis, godmode

-- Clear old GUI
if game.CoreGui:FindFirstChild("CYA_GUI") then game.CoreGui.CYA_GUI:Destroy() end

local UIS = game:GetService("UserInputService")
local Players = game:GetService("Players")
local lp = Players.LocalPlayer
local char = lp.Character or lp.CharacterAdded:Connect(function(c)
    flying = false
    flyBtn.Text = "Activar Vuelo"
    stopFlyLoop()
end)

-- FPS COUNTER (ESTILO DELTA)
local fpsLabel = Instance.new("TextLabel")
fpsLabel.Size = UDim2.new(0, 120, 0, 30)
fpsLabel.Position = UDim2.new(0, 10, 0, 140)
fpsLabel.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
fpsLabel.TextColor3 = Color3.fromRGB(0, 255, 0)
fpsLabel.TextSize = 18
fpsLabel.Font = Enum.Font.SourceSansBold
fpsLabel.Text = "FPS: 0"
fpsLabel.Parent = main

local last = tick()
local frames = 0
RunService.RenderStepped:Connect(function()
    frames = frames + 1
    local now = tick()
    if now - last >= 1 then
        fpsLabel.Text = "FPS: " .. frames
        frames = 0
        last = now
    end
end)
        end
    end)
    Frame.InputChanged:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseMovement then dragInput = input end
    end)
    UIS.InputChanged:Connect(function(input)
        if dragging and input == dragInput then
            local delta = input.Position - dragStart
            Frame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X,
                                       startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end)
end

-- GUI
local gui = Instance.new("ScreenGui", game.CoreGui)
gui.Name = "CYA_GUI"
gui.IgnoreGuiInset = true
gui.ResetOnSpawn = false
gui.DisplayOrder = 999999999

local main = Instance.new("Frame", gui)
main.Size = UDim2.new(0, 300, 0, 400)
main.Position = UDim2.new(0.3, 0, 0.3, 0)
main.BackgroundColor3 = Color3.fromRGB(25,25,25)
main.Active = true
main.BorderSizePixel = 0
dragify(main)

-- Close
local close = Instance.new("TextButton", main)
close.Text = "X"
close.Size = UDim2.new(0,32,0,32)
close.Position = UDim2.new(1,-36,0,4)
close.BackgroundColor3 = Color3.fromRGB(200,50,50)
close.TextColor3 = Color3.new(1,1,1)
close.MouseButton1Click:Connect(function() gui:Destroy() end)

-- Minimize
local min = Instance.new("TextButton", main)
min.Text = "-"
min.Size = UDim2.new(0,32,0,32)
min.Position = UDim2.new(1,-72,0,4)
min.BackgroundColor3 = Color3.fromRGB(70,70,70)
min.TextColor3 = Color3.new(1,1,1)

-- Floating orb
local orb = Instance.new("TextButton", gui)
orb.Size = UDim2.new(0,70,0,70)
orb.Position = UDim2.new(0.05,0,0.5,0)
orb.BackgroundColor3 = Color3.fromRGB(0,140,255)
orb.Text = ""
orb.Visible = false
orb.BorderSizePixel = 0
orb.Active = true
dragify(orb)
orb.MouseButton1Click:Connect(function() main.Visible = true orb.Visible = false end)
min.MouseButton1Click:Connect(function() main.Visible = false orb.Visible = true end)

-- Button creator
local function MakeBtn(txt, y)
    local b = Instance.new("TextButton", main)
    b.Size = UDim2.new(0,260,0,35)
    b.Position = UDim2.new(0,20,0,y)
    b.BackgroundColor3 = Color3.fromRGB(40,40,40)
    b.TextColor3 = Color3.new(1,1,1)
    b.Text = txt
    return b
end

-- Abilities
MakeBtn("Velocidad x4", 50).MouseButton1Click:Connect(function() hum.WalkSpeed = 64 end)
MakeBtn("Salto alto", 90).MouseButton1Click:Connect(function() hum.JumpPower = 160 end)
MakeBtn("Godmode", 130).MouseButton1Click:Connect(function() hum.Health = math.huge end)

-- Noclip
do
    local noclip = false
    MakeBtn("Noclip", 170).MouseButton1Click:Connect(function()
        noclip = not noclip
        while noclip do
            task.wait()
            for _,v in ipairs(char:GetDescendants()) do
                if v:IsA("BasePart") then v.CanCollide = false end
            end
        end
    end)
end

-- Fly
MakeBtn("Fly", 210).MouseButton1Click:Connect(function()
    loadstring(game:HttpGet("https://pastebin.com/raw/Y9bC8RjL"))()
end)

-- Invisibilidad
MakeBtn("Invisibilidad", 250).MouseButton1Click:Connect(function()
    if char:FindFirstChild("Head") then char.Head.Transparency = 1 end
    for _,v in ipairs(char:GetDescendants()) do
        if v:IsA("BasePart") then v.Transparency = 1 end
    end
end)

-- Dash
MakeBtn("Dash", 290).MouseButton1Click:Connect(function()
    hum.WalkSpeed = 120
    task.delay(0.4, function() hum.WalkSpeed = 16 end)
end)

-- Gravedad baja
MakeBtn("Gravedad baja", 330).MouseButton1Click:Connect(function()
    workspace.Gravity = 40
end)

-- Reset gravedad
MakeBtn("Gravedad normal", 370).MouseButton1Click:Connect(function()
    workspace.Gravity = 196.2
end)
